### ISSUE TITLE
interface ReadFile content is string instead of any

### ISSUE THREAD

**Issue by seranus** [fvilers/ngx-file-helpers#1]
title

**Comment by fvilers** [comment]
Hi! `content` is of type `any` because it varies depending on the `ReadMode` used (`arrayBuffer`, `binaryString`, `dataUrl`, `text`).

**Comment by cjamin** [comment]
That's the point: in `read-file.ts`, it is a `string`, not `any`.

**Comment by seranus** [comment]
https://github.com/fvilers/ngx-file-helpers/blob/6bfb9b15e1638b9e11b75b8dd37819696a7fdc54/src/read-file.ts#L9

**Comment by fvilers** [comment]
You guys are right, my bad. I'll fix that.

**Comment by fvilers** [comment]
Fix is available in 1.0.0-alpha.3

**Comment by cjamin** [comment]
Works like a charm. Thank you!
