### ISSUE TITLE
Angular6 support

### ISSUE THREAD

**Issue by ShukinDmitriy** [fvilers/ngx-file-helpers#12]
Try install this package with angular6.
`npm WARN ngx-file-helpers@1.1.0 requires a peer of @angular/core@^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN ngx-file-helpers@1.1.0 requires a peer of @angular/common@^5.0.0 but none is installed. You must install peer dependencies yourself.
`
Have you checked the performance in angular 6?

**Comment by fvilers** [comment]
Library has been updated (version 2.0.0) to support Angular 7.
