### ISSUE TITLE
Two filePicker in the same component html

### ISSUE THREAD

**Issue by Adenon** [fvilers/ngx-file-helpers#14]
how to bind with @ViewChild(FilePickerDirective) two filepicker in the same component ? 
my case is that Iam not able to use this.filePicker.reset() only on one of the two filePickers

**Comment by fvilers** [comment]
Starting from version 1.2.0, you can use a template reference variable as a selector. In your template:
```
<button ngxFilePicker #myFilePicker="ngxFilePicker">Browse</button>
```
In your component:
```
@ViewChild('myFilePicker')
private filePicker: FilePickerDirective; 
```
Now you should be able to bind any file picker in your component.

**Comment by Adenon** [comment]
I had try it, and try it even know, and it does not work :/

**Comment by Adenon** [comment]
please look at it, and mark the issue as opened

**Comment by fvilers** [comment]
> I had try it, and try it even now, and it does not work :/

Did you update the libary to 1.2.0?

**Comment by Adenon** [comment]
It wokrs now, thank you
