### ISSUE TITLE
License is missing

### ISSUE THREAD

**Issue by shodgson11** [fvilers/ngx-file-helpers#20]
The license is no longer showing in this project.  Has something changed?

**Comment by fvilers** [comment]
No, it doesn't. It's probably a mistake when I merged the `angular7` branch. The project remains under the MIT licence. I'll restore the file immediately.

**Comment by shodgson11** [comment]
Thank you for the lightning-fast reply and fix!

**Comment by fvilers** [comment]
You're welcome. Unfortunately, the file won't be present in the 2.0.0 bundle on NPM. :-(

**Comment by iulian-dragomir** [comment]
I'm a bit late to the party, but I saw the package was upgraded to angular 8 and now the License file is gone again.

**Comment by fvilers** [comment]
Ohh, I must have done something wrong then. Thanks letting me know !

**Comment by fvilers** [comment]
Version 3.0.1 has been published, and LICENSE has been restored (again), sorry for the inconvenience.
