### ISSUE TITLE
Changelog from 1.2.0 to 2.0.0

### ISSUE THREAD

**Issue by wescopeland** [fvilers/ngx-file-helpers#21]
`FileHelpersModule` has been renamed to `NgxFileHelpersModule`. The only way I found this was by going through the source code here on GitHub.

Please add a changelog or something w/ releases that shows when breaking changes happen.

**Comment by fvilers** [comment]
Hi @wescopeland. I'm sorry to read that you had trouble upgrading to the last version of the library. I took care to document all the breaking changes to the library [readme file](https://github.com/fvilers/ngx-file-helpers/tree/master/projects/ngx-file-helpers#breaking-changes). This is also documented on the [NPM package page](https://www.npmjs.com/package/ngx-file-helpers).

I should probably have it better highlighted in the main readme file at the repository root. I'll do my best to fix that.

**Comment by wescopeland** [comment]
Thank you for your response, and thank you for writing this library.

Cheers
