### ISSUE TITLE
Angular 8 - Sample code results parsing error - no directive with "exportAs" set to "ngxFilePicker"

### ISSUE THREAD

**Issue by b1gb1rd5** [fvilers/ngx-file-helpers#24]
Running through the example code results in the following error:
```
Template parse errors:
There is no directive with "exportAs" set to "ngxFilePicker" ("
<button
    ngxFilePicker
    [ERROR ->]#myFilePicker="ngxFilePicker">
    Browse
</button>")
```

EDIT: Example taken from [NPM page](https://www.npmjs.com/package/ngx-file-helpers)

**Comment by fvilers** [comment]
The library has been updated to Angular 8, feel free to reopen an issue if this is not fixed.
