### ISSUE TITLE
File with same name not triggering change event on file picked

### ISSUE THREAD

**Issue by smarlhens** [fvilers/ngx-file-helpers#26]
- **Package Name**: ngx-file-helpers
- **Package Version**: 2.0.0

**Describe the bug**
When I pick a file. Then I do whatever I want. Then I want to pick a file with the same name and change event is not triggered.

**To Reproduce**
1. Click on browsing button (with `ngxFilePicker`)
1. Select a file `a.extension`
1. Do whatever your want with your file
1. Try to select `a.extension` (same file or file with same name). `filePick` event is not triggered.

**Expected behavior**
Input change need to trigger `filePick` everytime.

PR : #25

**Comment by fvilers** [comment]
Hi ! Thanks for your submission, I'm currently on holidays, I'll look at your request as soon as I get back.
