### ISSUE TITLE
Angular v9 support issue

### ISSUE THREAD

**Issue by rernens** [fvilers/ngx-file-helpers#27]
When upgrading to angular v9  ( 9.0.7 then 9.1 )

while two dependencies warning were expected

> warning " > ngx-file-helpers@3.0.1" has incorrect peer dependency "@angular/common@^8.2.0".
> warning " > ngx-file-helpers@3.0.1" has incorrect peer dependency "@angular/core@^8.2.0".

i ran into an unexpected problem :

> Module not found: Error: Can't resolve '../../../../../../../../node_modules/ngx-file-helpers/lib/file-picker.directive'  in ....

usage in relevant component ts file :

> import { FilePickerDirective, ReadFile, ReadMode } from 'ngx-file-helpers';

> @ViewChild('myFilePicker')
>   private filePicker: FilePickerDirective;

relevant component parent module contains :

> import { NgxFileHelpersModule } from "ngx-file-helpers";

> @NgModule({
>   imports: [
>     (removed imports for clarity sakee),
>     NgxFileHelpersModule
>   ],
>   declarations: [
>  (removed declarations for clarity sake)
>   ]
> })

export class DocumentsModule { }

usage in component html file is :

> <button type="button"
>                 class="btn green custom btn-lg waves-effect waves-light"
>                 ngxFilePicker [readMode]="readMode"
>                 accept="pdf"
>                 #myFilePicker="ngxFilePicker"
>                 (filePick)="onFilePicked($event)"
>                 (readEnd)="onReadEnd()"
>           >
>           Selectionnez un document pdf
>         </button>

Angular v9.1
ngx-file-helpers 3.0.1

thanks for your help

**Comment by fvilers** [comment]
Hi ! Sorry for the inconvenience, version 4.0.0 which supports Angular 9 has been published. Give it a try and tell me if you still have any issue.

**Comment by rernens** [comment]
@fvilers 

hi Fabien, thanks for the fix. It works fine with one exception. 

ReadMode does not seem to be implemented anymore ( always return to '')

What is is the default readMode implemented and how can it be changed ?

Thanks for your help

**Comment by fvilers** [comment]
Hi !

> ReadMode does not seem to be implemented anymore ( always return to '')

I've just tried the demo shipped in this repository and the read mode is correctly displayed.

> What is is the default readMode implemented and how can it be changed ?

You can set the read mode by binding one of the enum value to it, like this :
Template :
```
<button
  type="button"
  ngxFilePicker
  [readMode]="readMode"
  accept="image/*"
  (readStart)="onReadStart($event)"
  (filePick)="onFilePicked($event)"
>
  Browse
</button>
```
Component :
```
export class FilePickerDemoComponent {
  public readMode = ReadMode.binaryString;
}
```

Available read modes are :
```
export declare enum ReadMode {
    arrayBuffer = 0,
    binaryString = 1,
    dataURL = 2,
    text = 3
}
```
