### ISSUE TITLE
Feature Request : Include file_extension

### ISSUE THREAD

**Issue by Debananda** [fvilers/ngx-file-helpers#29]
Can we include file_extension also to the directive like below
<button
  type="button"
  ngxFilePicker
  file_extension=".gif, .jpg, .png, .doc"
  (filePick)="file = $event">
  Browse
</button>

**Comment by fvilers** [comment]
This feature is already available under the `accept` attribute. It use the format described [here](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/accept).
