### ISSUE TITLE
Provide access to the underlying File object

### ISSUE THREAD

**Issue by chrisschaetzlein** [fvilers/ngx-file-helpers#3]
Thanks for this package, it is very helpful. 

However, as far as I understood, there is currently no way of accessing the native File object, when a file was selected. This would be extremely helpful for uploading files using the browser's FormData API.

**Comment by fvilers** [comment]
Hi, could you update to alpha.5 and see if it's good for you? I added a `underlyingFile` property to the file read object.

**Comment by chrisschaetzlein** [comment]
Great! Thank you!
