### ISSUE TITLE
Build error with 5.0.0

### ISSUE THREAD

**Issue by gloriousjob** [fvilers/ngx-file-helpers#34]
When I try to run ng serve or ng build, I get the following error:

Error: The target entry-point "ngx-file-helpers" has missing dependencies:
 - @angular/cdk/coercion

This was fine in 4.0.1 (upgraded to Angular 11) so I'm reverting back to that. Is this a dependency that should be in the package.json?

As a side note, I also saw this when I upgraded to 5.0.0:
ngx-file-helpers@5.0.0 requires a peer of @angular/core@11.0.0 but none is installed. You must install peer dependencies yourself.

I'm guessing this is missing something allowing a range instead of the exact version (I'm at the latest Angular 11).

**Comment by fvilers** [comment]
It's a regression and it's going to be fixed.

**Comment by fvilers** [comment]
Version 5.0.1 with a fix for this issue has been released.

**Comment by gloriousjob** [comment]
Thanks. I'm still seeing the peer dependency issue but the main concern is gone so I appreciate the swift response!

**Comment by fvilers** [comment]
Oh, I messed up with peer dependency for @angular/core. I released version 5.0.2 which correct this.
