### ISSUE TITLE
Support Angular 11.1, 11.2...

### ISSUE THREAD

**Issue by alogim** [fvilers/ngx-file-helpers#37]
Good morning,
could you please update the package so that it supports Angular 11.1/11.2 and so on? 

Currently npm shows the following:
```
Package "ngx-file-helpers" has an incompatible peer dependency to "@angular/common" (requires "~11.0.0" (extended), would install "11.2.0").
Package "ngx-file-helpers" has an incompatible peer dependency to "@angular/core" (requires "~11.0.0" (extended), would install "11.2.0").
```

Thank you!

**Comment by fvilers** [comment]
Hi, version 5.0.3 has been published with a fix with the peer dependencies. It normally should work with all 11.x version of angular.
