### ISSUE TITLE
Support Angular v12.x

### ISSUE THREAD

**Issue by alogim** [fvilers/ngx-file-helpers#43]
Good morning,
could you please update the package so that it supports Angular 12.x?

Currently npm shows the following with Angular 12.0.1:
ngx-file-helpers@5.0.3 requires a peer of @angular/common@^11.0.0 but none is installed. You must install peer dependencies yourself.
ngx-file-helpers@5.0.3 requires a peer of @angular/core@^11.0.0 but none is installed. You must install peer dependencies yourself.

Thank you!

**Comment by fvilers** [comment]
Sorry for the late reply, I've been quite busy lately. I'm working on this right now, expect an update asap.

**Comment by fvilers** [comment]
Version 6.0.0 has been released. Enjoy !
