### ISSUE TITLE
Support Angular 13

### ISSUE THREAD

**Issue by gloriousjob** [fvilers/ngx-file-helpers#47]
Angular 13 enables Ivy and removes the View Engine. Please update dependencies and configs to support Angular 13.

The following warning shows during a compile:
⠙ Generating browser application bundles (phase: setup)...Processing legacy "View Engine" libraries:
- ngx-file-helpers [es2015/esm2015] (git+https://github.com/fvilers/ngx-file-helpers.git)
Encourage the library authors to publish an Ivy distribution.

**Comment by sandersdevelopments** [comment]
+1 for this :-) We can't migrate to angular 13 bc we love this package too much

**Comment by fvilers** [comment]
I'll have to find some time to do it properly. I can't promise anything, but this will be done in January ;-)

**Comment by fvilers** [comment]
Version 7.0.0 has been released which should support Angular 13 and Ivy. Please let me know if something is wrong.
