### ISSUE TITLE
Can't use this in filter callback

### ISSUE THREAD

**Issue by coyoteecd** [fvilers/ngx-file-helpers#48]
The filter callback is passed "as-is" to the Array.filter function here: https://github.com/fvilers/ngx-file-helpers/blob/0a5839043091a871102fbf1fe2b7f657b1b0bf41/projects/ngx-file-helpers/src/lib/file-handler.ts#L28

The side-effect is that if your callback needs some data from the component hosting the dropzone, it can't access it through the "this" reference. This makes the filter much less useful when the dropzone is part of a generic (configurable) component - think of filtering based on file size taken from the component input param, for example.

**Comment by fvilers** [comment]
Fixed in version 6.0.1
