### ISSUE TITLE
version mismatch for module

### ISSUE THREAD

**Issue by tirlipinpon** [fvilers/ngx-file-helpers#5]
installed  "ngx-file-helpers": "^1.0.0-alpha.5",

but on compilation have this error: 

ERROR in Metadata version mismatch for module /node_modules/ngx-file-helpers/ngx-file-helpers.d.ts, found version 4, expected 3, resolving symbol AppModule in /src/app/app.module.ts, resolving symbol AppModule in /src/app/app.module.tsHash:

**Comment by fvilers** [comment]
What version of Angular do you use?

**Comment by tirlipinpon** [comment]
Hello, my core is on "^4.3.6".  @angular/cli on  1.3.2", but this problem seems disappeared for now. sorry for the disturbance. some compilation issue a some point.

**Comment by fvilers** [comment]
Ok, I'll close the issue then.
