### ISSUE TITLE
Update to Angular 14

### ISSUE THREAD

**Issue by sandersdevelopments** [fvilers/ngx-file-helpers#56]
Hey :-) 

Would you mind to update to Angular 14 / merge this https://github.com/fvilers/ngx-file-helpers/pull/55 PR and publish it to npmjs.com? 
Then our application update won't be blocked anymore 👍  
Thanks in advance!

**Comment by fvilers** [comment]
Version 8.0.0 with Angular 14 support has been published to npm.
