### ISSUE TITLE
Unable to select big files

### ISSUE THREAD

**Issue by glennverschooren** [fvilers/ngx-file-helpers#57]
The Angular directives (ngxFilePicker and ngxFileDropzone) can not handle big files (4GB)
The [FileReader](https://developer.mozilla.org/en-US/docs/Web/API/FileReader)  is throwing the following error  **"The requested file could not be read, typically due to permission problems that have occurred after a reference to a file was acquired."** after selecting a big file from the file system. (PS: The error does not occur when selecting a "small" file )

I think that the file should be read chunk by chunk to prevent this error? => (https://gist.github.com/alediaferia/cfb3a7503039f9278381)
Is there a reason why the selected files are read?

**Comment by fvilers** [comment]
At the time I wrote the library, I thought it was easier for the directives consumer to have the file already read and that the content would be immediately available. I did not had a use case for files that large. Did you try to pick a 4GB file with a different [read mode](https://github.com/fvilers/ngx-file-helpers/tree/master/projects/ngx-file-helpers#readmode) ?

**Comment by glennverschooren** [comment]
@fvilers Thanks for the quick response! :)

I've tried all different read modes but unfortunately without any success :)

**Comment by glennverschooren** [comment]
Uploading big files (movies etc) to [massive.io](https://massive.io/)

**Comment by fvilers** [comment]
Could you checkout the related PR and see if it suits your needs ? At the moment, I'll leave the responsibility to read in chunks to the consumer as I feel it's beyond the responsibility of the directive.

**Comment by fvilers** [comment]
@glennverschooren

**Comment by glennverschooren** [comment]
@fvilers Approved the pull request. Thx 👍

**Comment by fvilers** [comment]
Version 8.1.0 has been released to fix this issue.
