### ISSUE TITLE
ReadMode deprecated without an alternative

### ISSUE THREAD

**Issue by coyoteecd** [fvilers/ngx-file-helpers#59]
Today I updated to `ngx-file-helpers` v8.1.0 and I get the following deprecation warnings (we use deprecation eslint plugin):
`warning  'ReadMode' is deprecated. ReadMode will be renamed to Pascal Casing in the 9.0.0 release`

While I understand the intent of pre-announcing users of a future change, I think this is a misuse of the `@deprecated` tag. If an API is deprecated, you should provide an alternative in the same version.

Could you please republish an 8.1.1 without the deprecation?

**Comment by fvilers** [comment]
Version 8.1.1 has been published. Thanks for your report !
