### ISSUE TITLE
2 packages doing the same thing

### ISSUE THREAD

**Issue by AckerApple** [fvilers/ngx-file-helpers#7]
Hey, save people time.

Point them here: https://www.npmjs.com/package/angular-file

Always advantages to having different ways of doing things.

Farewell. I wonder if you tried angular-file before reinventing another wheel?

**Comment by fvilers** [comment]
Hi, I didn't know of angular-fire before. The package I maintain is the portage of an AngularJS package I was already maintaining for quiet a moment. Like you said, always good to have multiple ways of doing things.
